# Generated by Django 6.0 on 2026-01-09 13:42

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_column='nom', max_length=25)),
                ('telephone', models.CharField(db_column='telephone', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Espace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('capacite', models.PositiveIntegerField(help_text='Nombre maximum de personnes')),
                ('prix_journalier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('est_disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='eventImage')),
                ('titre_stockage', models.CharField(db_column='nom_titre', max_length=30)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('_nombre_de_places', models.SmallIntegerField(db_column='nombre_de_places')),
                ('description', models.TextField(blank=True, null=True)),
                ('type_evenement', models.CharField(editable=False, max_length=50)),
                ('espace', models.ManyToManyField(to='maison.espace')),
                ('intervenant', models.ManyToManyField(to='maison.acteur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=50)),
                ('username', models.CharField(db_column='user_name', max_length=150, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EvenementCulturel',
            fields=[
                ('evenement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maison.evenement')),
                ('genre', models.CharField(max_length=50)),
            ],
            bases=('maison.evenement',),
        ),
        migrations.CreateModel(
            name='EvenementEconomique',
            fields=[
                ('evenement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maison.evenement')),
                ('secteur', models.CharField(max_length=50)),
            ],
            bases=('maison.evenement',),
        ),
        migrations.CreateModel(
            name='EvenementPolitique',
            fields=[
                ('evenement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maison.evenement')),
                ('organisation', models.CharField(max_length=50)),
            ],
            bases=('maison.evenement',),
        ),
        migrations.CreateModel(
            name='EvenementSocial',
            fields=[
                ('evenement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maison.evenement')),
                ('cause', models.CharField(max_length=50)),
            ],
            bases=('maison.evenement',),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emission', models.DateField(default=django.utils.timezone.now)),
                ('nombre_jour', models.PositiveIntegerField(default=1)),
                ('montant_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('PAYEE', 'Payée'), ('ATTENTE', 'En attente')], default='ATTENTE', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_recues', to=settings.AUTH_USER_MODEL)),
                ('espace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maison.espace')),
                ('staff', models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('confirme', 'Confirmé'), ('paye', 'Payé'), ('annule', 'Annulé')], default='attente', max_length=10)),
                ('montant_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('espace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maison.espace')),
            ],
        ),
        migrations.CreateModel(
            name='TarifEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('STD', 'Standard'), ('VIP', 'VIP'), ('VVIP', 'VVIP')], max_length=10)),
                ('prix', models.PositiveIntegerField()),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='maison.evenement')),
            ],
            options={
                'verbose_name': "Tarif de l'événement",
                'verbose_name_plural': 'Tarifs des événements',
                'ordering': ['prix'],
                'unique_together': {('evenement', 'categorie')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_paye', models.BooleanField(default=False)),
                ('code_barre_qr', models.CharField(blank=True, max_length=150)),
                ('numero_place', models.IntegerField()),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('choix_tarif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maison.tarifevenement')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
