# Generated by Django 6.0 on 2026-01-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
    ]
