# Generated by Django 6.0 on 2026-01-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison', '0002_ticket_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='facture_telechargee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_telecharge',
            field=models.BooleanField(default=False),
        ),
    ]
